import React from 'react';
import {Button, Divider, TextField} from "@mui/material";
import UserMessage from "./UI/UserMessage";

const Index = () => {

    const chat = [
        {user: {avatar: "https://picsum.photos/200/300?grayscale", name: "Avatar 1", active: true, last_data: "12.08"}, time: 12.04, message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", owner: "you"},
        {user: {avatar: "https://picsum.photos/200/300?grayscale", name: "Avatar 2", active: false, last_data: "11.08"}, time: 13.04, message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."},
        {user: {avatar: "https://picsum.photos/200/300?grayscale", name: "Avatar 3", active: false, last_data: "12.08"}, time: 14.04, message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", owner: "you"},
        {user: {avatar: "https://picsum.photos/200/300?grayscale", name: "Avatar 4", active: true, last_data: "13.08"}, time: 11.04, message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.."},
        {user: {avatar: "https://picsum.photos/200/300?grayscale", name: "Avatar 1", active: true, last_data: "12.08"}, time: 12.04, message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", owner: "you"},
        {user: {avatar: "https://picsum.photos/200/300?grayscale", name: "Avatar 1", active: true, last_data: "12.08"}, time: 12.04, message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", owner: "you"},
        {user: {avatar: "https://picsum.photos/200/300?grayscale", name: "Avatar 1", active: true, last_data: "12.08"}, time: 12.04, message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", owner: "you"},
        {user: {avatar: "https://picsum.photos/200/300?grayscale", name: "Avatar 1", active: true, last_data: "12.08"}, time: 12.04, message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", owner: "you"},
        {user: {avatar: "https://picsum.photos/200/300?grayscale", name: "Avatar 1", active: true, last_data: "12.08"}, time: 12.04, message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", owner: "you"},
    ]

    return (
        <div className="w-full h-fit pb-4 relative">
            <div className="w-full h-fit h-max-182 justify-start items-center text-center flex flex-col overflow-y-scroll overflow-x-hidden pt-2">
                {chat.map((e) => {
                    return(<UserMessage message={e}/>)
                })}
            </div>
            <div className="w-full h-16"></div>
            <div className="w-full h-20 flex flex-row justify-center items-center text-center absolute bottom-2">
                <TextField id="outlined-basic" label="Message" variant="outlined" className="mr-4 w-8/12"/>
                <Button color="success" variant="outlined" className="h-14">Send message</Button>
            </div>
        </div>
    );
};

export default Index;